# Generated by Django 3.2.13 on 2025-03-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porduct',
            new_name='Product',
        ),
    ]
